---
- name: Simple rulebook
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 6
  
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: Say Hello World
          organization: Default