---
- name: Simple rulebook with webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
       host: 0.0.0.0
       port: 5000
  
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: Say Hello World
          organization: Default