---
- name: Simple rulebook with webhook
  hosts: all
  sources:
    - ansible.eda.webhook: # This is for local testing, Event Stream handles this in AAP
       host: 0.0.0.0
       port: 5000
  
  rules:
    - name: Run job template
      #condition: event.payload.message == "Incoming message"
      action:
        run_job_template:
          name: "New RHEL Server RITM from ServiceNow"
          organization: "Default"
          job_args:
            extra_vars:
              instance_name: "{{ event.payload['variables']['sn_vm_name'] }}"